// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddFolder(arg1, arg2) {
  return window['go']['main']['App']['AddFolder'](arg1, arg2);
}

export function AddRequest(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddRequest'](arg1, arg2, arg3, arg4);
}

export function AddRootFolder(arg1) {
  return window['go']['main']['App']['AddRootFolder'](arg1);
}

export function DeleteItem(arg1) {
  return window['go']['main']['App']['DeleteItem'](arg1);
}

export function GetRequests() {
  return window['go']['main']['App']['GetRequests']();
}

export function SetRequestsPatch(arg1) {
  return window['go']['main']['App']['SetRequestsPatch'](arg1);
}
