// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {models} from '../models';

export function AddFolder(arg1:string,arg2:string):Promise<string>;

export function AddRequest(arg1:string,arg2:string,arg3:string,arg4:string):Promise<string>;

export function GetRequests():Promise<models.Requests>;

export function SetRequestsPatch(arg1:Record<string, any>):Promise<void>;
